config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :print_jobs
  resources :printers
 #  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'

  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end


  get 'home/index'

  resources :jobs
  resources :clients
  #root :to =>'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :client
  has_many  :print_jobs
  before_create :calculate_completeper

  private
    def calculate_completeper
      self.completeper = quantity.to_i - completed_amount.to_i
    end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def complete
      job.quantity - job.completed
  end

  def index
    @jobs = Job.all

    # print  Jobs  Total
    #@sinprintjobs = PrintJob.where(:job_id => @job.id).sum(:quantity)
    #@jobs_complete = diffrence [:Job.quantity ]- [:Job.completed]

    #@completepercent = <%=job_completed / job_completed %
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @jobs = Job.find(params[:id])
    @jobss = Job.all

    @print_jobs = PrintJob.where(:job_id => @job.id)
    #@sinprintjobs=  PrintJob.sum(:quantity)
    @sinprintjobs = PrintJob.where(:job_id => @job.id).sum(:quantity)
  #  @percompe =  PrintJob.where(:job_id => @job.id) -> (@sinprintjobs / @job.quantity)
      @total_prints =  PrintJob.where(:job_id => @job.id).count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
   @job.remaider = params[:quantity].to_i - params[:completed].to_i
   @job.save!

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :client_id, :description, :quantity, :datein, :duedate, :completeper, :expectedin, :completed, :status, :comment)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :job_name %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :name,:include_blank => " Add client..", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :job_quantity %>
  </div>

  <div class="field">
    <%= form.label :datein %>
    <%= form.datetime_select :datein, id: :job_datein %>
  </div>

  <div class="field">
    <%= form.label :duedate %>
    <%= form.datetime_select :duedate, id: :job_duedate %>
  </div>
  <div class="field">
    <%= form.label :completed %>
    <%= form.number_field :completed, id: :job_completed %>
  </div>

  <div class="field">
    <%= form.label :expectedin %>
    <%= form.text_field :expectedin, id: :job_expectedin %>
  </div>

  <div class="field">
    <%= form.label :status %>    
    <%= form.select :status, options_for_select(%w[ In_Progress Stalled Complete  On_Hold ]) %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :job_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<section class="content-header">
    <h1>
        Print    Jobs
        <small>ChApp</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Print   Jobs</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">

          <div class="box">
                  <div class="box-header">
                      <h3 class="box-title">Print  Jobs</h3>

                      <div class="pull-right">
          						    <%= link_to "Add A New Print  Job", new_print_job_path, :class => 'btn btn-flat btn-primary' %>
          					  </div>
                  </div><!-- /.box-header -->
                  <div class="box-body no-padding">


                    <table class="table   table-striped">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Client</th>
                          <th>Description</th>
                          <th>Quantity</th>
                          <th>Date In</th>
                          <th>Due Date</th>
                          <th>Completed</th>
                          <th>Complete (%)</th>
                          <th>Expected In (hrs)</th>
                          <th>Status</th>
                          <th>Comment</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @jobs.each do |job| %>
                          <tr>

                            <td><%= link_to job.name, job %></td>
                            <td><%= job.client.name %></td>
                            <td><%= job.description %></td>
                            <td><%= job.quantity %></td>
                            <td><%= job.datein %></td>
                            <td><%= job.duedate %></td>
                            
                            <td><%= number_with_precision(@sprintjobs, :precision => 2, :delimiter => ',') %></td>

                            <td><%= job.completed %></td>
                            <td><%= job.expectedin %></td>

                            <td><%= job.status %></td>
                            <td><%= job.comment %></td>
                            <td><%= link_to 'Show', job %></td>
                            <td><%= link_to 'Edit', edit_job_path(job) %></td>
                            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div><!-- /.box-body -->
              </div><!-- /.box -->
        </div>
    </div>
</section>


<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.min.js"></script>

<section class="content-header">
    <h1>
        <summary>Summary</summary>
        <small>Clients' Jobs</small>
    </h1>
    <ol class="breadcrumb">
        <li> <i class="fa fa-dashboard"></i>  Home</a></li>
        <li class="active">Jobs   Summary</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">

    <div class="col-md-6">

      <div class="box">
            <div class="box-header">
                <strong class="box-title">Client Jobs   Details </strong>
            </div><!-- /.box-header -->
	        <div class="box-body">

            <p>
              <strong>Name:</strong>
              <%= @job.name %>
            </p>

            <p>
              <strong>Client:</strong>
              <%= @job.client.name %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= @job.description %>
            </p>

            <p>
              <strong>Quantity:</strong>
              <%= @job.quantity %>
            </p>

            <p>
              <strong>Datein:</strong>
              <%= @job.datein %>
            </p>

            <p>
              <strong>Duedate:</strong>
              <%= @job.duedate %>
            </p>

            <p>
              <strong>Completed:</strong>

            <%= number_with_precision(@sinprintjobs, :precision => 2, :delimiter => ',') %>
            </p>
            <p>
              <strong>%  Complete:</strong>
              <%= @job.percentcomplete %>
            </p>

            <p>
              <strong>Expectedin:</strong>
              <%= @job.expectedin %>
            </p>

            <p>
              <strong>Status:</strong>
              <%= @job.status %>
            </p>

            <p>
              <strong>Comment:</strong>
              <%= @job.comment %>
            </p>
	        </div><!-- /.box-body -->
          </div><!-- /.box -->
    </div>
    <div class="col-md-6">

      <div class="box">
            <div class="box-header">
                <h3 class="box-title">Job  Charts </h3>
            </div><!-- /.box-header -->


            <div class="chart">
              <div class="chart">
                <canvas id="jobChart" width="400" height="280"></canvas>
              </div>

          </div><!-- /.box-body -->
          </div><!-- /.box -->
    </div>

    <div class="col-md-12">
      <div class="box">
            <div class="box-header">
                <h3 class="box-title">Print  Jobs</h3>
            </div><!-- /.box-header -->
	        <div class="box-body">
            <table class="table table-bordered">

              <thead  class="success">
                <tr>
                  <th>Job  Code</th>
                  <th>Job</th>
                  <th>Description</th>
                  <th>Quantity</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @print_jobs.each do |print_job| %>
                  <tr>
                    <td><%= print_job.code %></td>
                    <td><%= print_job.job.name %></td>
                    <td><%= print_job.Description %></td>
                    <td><%= print_job.quantity %></td>
                    
                    <td><%= link_to 'Show', print_job %></td>

                  </tr>

                <% end %>

                <tr>
                  <td></td>
                  <td></td>
                  <td>Totals</td>
                  <td><%= number_with_precision(@sinprintjobs, :precision => 2, :delimiter => ',') %></td>


                  <td><%=  %></td>
                </tr>
              </tbody>
            </table>


	        </div><!-- /.box-body -->
          </div><!-- /.box -->
    </div>



</div>
</section>



<script>
      var ctx = document.getElementById("jobChart");
      var jobChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: ["Required ", "Completed", "Print  Jobs"],
              datasets: [{
                  label: 'Total',
                  data: [<%= @job.quantity %>, <%= @sinprintjobs %> , <%= @total_prints %>],
                  backgroundColor: [
                      'rgba(0, 0, 255, 1)',
                      'rgba(75, 255, 5, 1)',

                  ],
                  borderColor: [
                      'rgba(0, 0, 255, 1)',
                      'rgba(75, 255, 5, 1)',

                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });
</script>