config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :print_jobs
  resources :printers
 #  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'

  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end


  get 'home/index'

  resources :jobs
  resources :clients
  #root :to =>'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @clients = Client.find(params[:id])

    @jobs = Job.where(:client_id => @client.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :description, :contactperson, :phone, :officeline, :email, :building, :street, :location, :city, :country)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :client_description %>
  </div>

  <div class="field">
    <%= form.label :contactperson %>
    <%= form.text_field :contactperson, id: :client_contactperson %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :client_phone %>
  </div>

  <div class="field">
    <%= form.label :officeline %>
    <%= form.text_field :officeline, id: :client_officeline %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email %>
  </div>

  <div class="field">
    <%= form.label :building %>
    <%= form.text_field :building, id: :client_building %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :client_street %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :client_location %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :client_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :client_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Clients
        <small>ChApp</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Clients</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">

          <div class="box">
                  <div class="box-header">
                      <h3 class="box-title">Client Companies</h3>

                      <div class="pull-right">
          						    <%= link_to "Add A New client", new_client_path, :class => 'btn btn-flat btn-primary' %>
          					  </div>
                  </div><!-- /.box-header -->
                  <div class="box-body no-padding">


                      <table class="table table-stripped">
                        <tr>
            							<td><h4>Name</h4></td>
            							<td><h4>Email</h4></td>
            							<td><h4>Contact Person</h4></td>
            							<td><h4> phone</h4></td>

            							<td></td>
            						</tr>

            						<% @clients.each do |client| %>
            							<tr>
            								<td> <%= link_to client.name, client %> </td>
                            <td><%= client.description %></td>
                            <td><%= client.contactperson %></td>
                            <td><%= client.phone %></td>
                            <td><%= client.officeline %></td>
                            <td><%= client.email %></td>
            								<td>
                              <%= link_to 'View client', client %>
            									<%= link_to 'Edit', edit_client_path(client) %>
            									<%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %>
            								</td>
            							</tr>
            						<% end %>
            					</table>
                  </div><!-- /.box-body -->
              </div><!-- /.box -->
        </div>
    </div>
</section>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Client Companies
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Clients</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">

    <div class="col-md-12">

      <div class="box">
            <div class="box-header">
                <h3 class="box-title">Company Details</h3>
            </div><!-- /.box-header -->
	        <div class="box-body">

				<p>
				  <b>Name:</b>
				  <%= @client.name %>
				</p>

        <p>
          <strong>Description:</strong>
          <%= @client.description %>
        </p>

        <p>
          <strong>Contactperson:</strong>
          <%= @client.contactperson %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @client.phone %>
        </p>

        <p>
          <strong>Officeline:</strong>
          <%= @client.officeline %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @client.email %>
        </p>

        <p>
          <strong>Building:</strong>
          <%= @client.building %>
        </p>

        <p>
          <strong>Street:</strong>
          <%= @client.street %>
        </p>

        <p>
          <strong>Location:</strong>
          <%= @client.location %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @client.city %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @client.country %>
        </p>
	        </div><!-- /.box-body -->
          </div><!-- /.box -->
    </div>

    <div class="col-md-12">
      <div class="box">
            <div class="box-header">
                <h3 class="box-title">JObs</h3>
            </div><!-- /.box-header -->
	        <div class="box-body">
	           		<table class="table table-striped">
					 <tr>
						<td><h4>job ID</h4></td>
						<td><h4>JOb</h4></td>

						<td>Client<h4></h4></td>

						<td><h4>Date in</h4></td>
						<td><h4>Due  Date</h4></td>
						<td><h4>Exepected  In</h4></td>

						<td><h4>Status</h4></td>
						<td><h4>Comment</h4></td>
						<td><h4>Quantity</h4></td>

						<td><h4>Description</h4></td>
						<td><h4>Actions</h4></td>
					</tr>

					<% @jobs.each do |job| %>
						<tr>
							<td><%= job.id %></td>

							<td> <%= link_to @client.name, job %> </td>

							<td><%= job.client.name %></td>
							<td><%= job.datein %></td>
							<td><%= job.duedate %></td>

							<td><%= job.expectedin %></td>

							<td><%= job.status %></td>
							<td><%= job.comment %></td>

							<td><%= job.quantity %></td>

							<td><%= job.description %></td>

							<td>
								<%= link_to 'Edit', edit_job_path(job) %>
				    			<%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
							</td>

						</tr>
					<% end %>

				</table>

	        </div><!-- /.box-body -->
          </div><!-- /.box -->
    </div>



</div>
</section>