config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :print_jobs
  resources :printers
 #  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'

  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end


  get 'home/index'

  resources :jobs
  resources :clients
  #root :to =>'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/printer.rb
class Printer < ApplicationRecord
  belongs_to :job
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]

  # GET /printers
  # GET /printers.json
  def index
    @printers = Printer.all
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: 'Printer was successfully updated.' }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: 'Printer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.require(:printer).permit(:name, :description, :operator)
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/printers/_form.html.erb
<%= form_with(model: printer, local: true) do |form| %>
  <% if printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(printer.errors.count, "error") %> prohibited this printer from being saved:</h2>

      <ul>
      <% printer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :printer_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :printer_description %>
  </div>

  <div class="field">
    <%= form.label :operator %>
    <%= form.text_field :operator, id: :printer_operator %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/printers/edit.html.erb
<h1>Editing Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Show', @printer %> |
<%= link_to 'Back', printers_path %>

app/views/printers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Printers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Operator</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @printers.each do |printer| %>
      <tr>
        <td><%= printer.name %></td>
        <td><%= printer.description %></td>
        <td><%= printer.operator %></td>

        <td><%= link_to 'Show', printer %></td>
        <td><%= link_to 'Edit', edit_printer_path(printer) %></td>
        <td><%= link_to 'Destroy', printer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Printer', new_printer_path %>

app/views/printers/new.html.erb
<h1>New Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Back', printers_path %>

app/views/printers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @printer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @printer.description %>
</p>

<p>
  <strong>Operator:</strong>
  <%= @printer.operator %>
</p>

<p>
  <strong>Job:</strong>
  <%= @printer.job %>
</p>

<%= link_to 'Edit', edit_printer_path(@printer) %> |
<%= link_to 'Back', printers_path %>