config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :print_jobs
  resources :printers
 #  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'

  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end


  get 'home/index'

  resources :jobs
  resources :clients
  #root :to =>'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/navigation/_footer.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    ...products  for   mankind
  </div>
  <strong>
    Copyright © 2017
    <a href="#"> Sprint   Olive  k  Ltd</a>
  </strong>
  All rights reserved.
</footer>

app/views/layouts/navigation/_header.erb
<header class="main-header">
  <a class="logo" href="/">
Chrystals   App
</a>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope-o">
            </i><span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 4 messages
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#"> </a>
                  <div class="pull-left">
                    <img class="img-circle" alt="User Image" src="http://placehold.it/160x160"> </img>
                  </div>
                  <h4>
                    Sender Name
                    <small>
                    <i class="fa fa-clock-o">
                    </i>5 mins
                    </small>
                  </h4>
                  <p>
                    Message Excerpt
                  </p>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> See All Messages</a>
            </li>
          </ul>
        </li>
        <li class="dropdown notifications-menu">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell-o">
            </i><span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 10 notifications
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                <i class="ion ion-ios-people info">
                </i>Notification title
                </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> View all</a>
            </li>
          </ul>
        </li>
        <li class="dropdown tasks-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-flag-o">
            </i><span class="label label-danger">9</span>
            </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 9 tasks
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                  </a>
                  <h3>
                    Design some buttons
                  <small class="pull-right">20%</small>
                  </h3>
                  <div class="progress xs">
                    <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" class="progress-bar progress-bar-aqua" role="progressbar" style="width: 20%">
<span class="sr-only">20% Complete</span>
</div>
                  </div>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> View all tasks</a>
            </li>
          </ul>
        </li>
        <li class="dropdown user user-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
          <span class="hidden-xs">Paul</span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img class="img-circle" alt="User Image" src="http://placehold.it/160x160"> </img>
              <p>
                Njuguna
                <small></small>
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-left">
                <a class="btn btn-default btn-flat" href="#"> Profile</a>
              </div>
              <div class="pull-right">
                <a class="btn btn-default btn-flat" href="#"> Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/navigation/_layout.erb
<%= render "layouts/navigation/header" %>
<%= render "layouts/navigation/sidebar" %>

app/views/layouts/navigation/_sidebar.erb
<% if signed_in? %>
<div class="main-sidebar">
  <div class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
      </div>
      <div class="pull-left info">
          <p>Hello, <%= current_user.email %></p>

          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <form action="#" class="sidebar-form" method="get">
      <div class="input-group">
        <input class="form-control" name="q" placeholder="Search..." type="text" />
        <span class="input-group-btn">
        <button class="btn btn-flat" id="search-btn" name="search" type="submit">
        <i class="fa fa-search">
        </i></button></span>
      </div>
    </form>
    <ul class="sidebar-menu">
        <li class="active">
            <a href="#">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-bar-chart-o"></i>
                <span> Users</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="<%= users_path %>"><i class="fa fa-angle-double-right"></i> View All</a></li>
                <li><a href="<%= users_path %>"><i class="fa fa-angle-double-right"></i> Add New</a></li>

            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Manage  jobs</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="<%= jobs_path %>"><i class="fa fa-angle-double-right"></i>View All  jobs</a></li>
                <li><a href="<%= new_job_path %>"><i class="fa fa-angle-double-right"></i> Add New</a></li>

            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-envelope"></i>
                <span>Clients</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="<%= clients_path %>"><i class="fa fa-angle-double-right"></i>All Clients</a></li>
                <li><a href="<%= new_client_path %>"><i class="fa fa-angle-double-right"></i> Add client</a></li>

            </ul>
        </li>


    </ul>
  </div>
</div>
<% end %>